class RustRawStringSearcher:
    def __new__(cls) -> "RustRawStringSearcher": ...
    def add_word(self, word: str, msg: str, error_type: str, rule_id: str) -> None: ...
    def build(self) -> None: ...
    def search_raw(self, word: str) -> list[tuple[str, str, int, int, str]]: ...