from typing import Any

class RustRawStringSearcher:
    def __new__(cls) -> "RustRawStringSearcher": ...
    def add_word(self, word: str, msg: str, error_type: str, rule_id: str) -> None: ...
    def build(self) -> None: ...
    def search_raw(self, word: str) -> list[tuple[str, str, int, int, str]]: ...

class RustSpellChecker:
    def __new__(cls) -> "RustSpellChecker": ...
    def set_strings(self, strings: list[str]) -> None: ...
    def add_rule(self, encoded_rule: tuple) -> None: ...
    def check(self, tokens: list[Any]) -> list[Any]: ...
